### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by harphere** [whizzzkid/home-infrastructure#2]
It's not clear to me on what the Authorized redirect URI should look like in Google console.
I've tried multiple variations `https://oauth.example.com/_oauth` is one attempt but when I go to `https://home.example.com` it results in `The redirect URI in the request, https://auth.home.example.com/_oauth, does not match the ones authorized for the OAuth client.`

Can you kindly advise on the steps required to make this work?

Thanks!

**Comment by whizzzkid** [comment]
@harphere based on https://github.com/thomseddon/traefik-forward-auth#provider-setup the oauth redirect URI in console would be: `https://<tfa-service>.<server>.<domain>.<tld>/_oauth`

Apologies for a very late response, but I hope it helps!
